### PR TITLE
Fix InitializeSpecShim is not defined issue

### LINKED ISSUE #63: `InitializeSpecShim` is not defined
When using the non-polyfilled version of sites, `InitializeSpecShim` is called which doesn't exist. I'm guessing it should be using [this function from the polyfill](https://github.com/googlevr/webvr-polyfill/blob/7023c2b840a3a41d85ff09b1e9db1f673824338c/src/webvr-polyfill.js#L238-L257), and if so, we should explicilty make it clear that that function should be exposed from the polyfill

### PR DESCRIPTION
**Pull request by huningxin**
Fix #63

### CODE REVIEW

**Comment by huningxin** [comment]
@toji , PTAL. Thanks!

**Comment by toji** [comment]
Hm, upon looking at this it seems that the function name was a typo? We probably want the pages to be calling "InstallWebVRSpecShim" instead, to avoid ambiguity and having two names for the same thing. As for the function not being exported, that should be fixed in the main polyfill library so that we don't lose this change the next time we update from source.

**Comment by huningxin** [comment]
From the log, it seems the [`InstallWebVRSpecShim` patch](https://github.com/toji/webvr-samples/commit/c78f94b0a06ebfa7a32ac3c33faa1fa126f96771) is lost in latest [webvr-polyfill update commit](https://github.com/toji/webvr.info/commit/81d1b55a23c6f115b32c18fefca9f0fff3fee992).

Fix in the webvr-polyfill library sounds a better solution. I will do that.

**Comment by huningxin** [comment]
I send a PR https://github.com/googlevr/webvr-polyfill/pull/259 to expose `InstallWebVRSpecShim`. Once webvr-polyfill is updated, all samples need to replace `InitializeSpecShim` with `InstallWebVRSpecShim`.

**Comment by huningxin** [comment]
Updated the PR, @toji , please take another look. Thanks!

**Comment by huningxin** [comment]
ping @toji . Thanks!

**Comment by toji** [comment]
Thanks for your work on this and sorry it was never merged. The issue has been rendered moot by #85

**Pull request closed without merging**
