### PR TITLE
Update webvr-polyfill to e2958490653 (0.10.8+)

### PR DESCRIPTION
**Pull request by klausw**
This should fix the rapid spinning issue caused by degree/radian confusion.

Fixes issue #105.

### CODE REVIEW

**Comment by klausw** [comment]
Sorry about the noise, I unexpectedly got changes from a different branch pushed into this PR. I've reset it to the originally intended single commit.

**Comment by klausw** [comment]
@jsantell has some pending changes in https://github.com/immersive-web/webvr-polyfill-dpdb to add devices including Pixel 2 XL / Pixel 3 XL to the database, this is necessary to get a usable polyfill display on these devices. Looks like this would normally propagate via the https://github.com/immersive-web/cardboard-vr-display to the https://github.com/immersive-web/webvr-polyfill repository, but those don't have new releases yet.

@toji - do you want me to wait for a new webvr-polyfill release that includes these, or do that in a followup change?

**Comment by jsantell** [comment]
Pushed out updates to the polyfills with the latest Pixel dpdb values, v0.10.10

**Comment by klausw** [comment]
Abandoning this one, I've merged the update to official 0.10.10 in https://github.com/toji/webvr.info/pull/107 .

**Pull request closed without merging**
