### PR TITLE
spruce up content and link to new full instructions

### PR DESCRIPTION
**Pull request by cvan**
Spruced up the content and added various links, namely links to instructions for downloads/setup/info. for the various browser/headset/OS platform combinations (which are currently/temporarily being hosted [here](https://github.com/Web-VR/iswebvrready/wiki/), until I/@caseyyee embeds/rejigs/finds a new home/format for them).

### CODE REVIEW

**Comment by cvan** [comment]
for a lighter page weight and more readable experience, I also made these changes:

* removed the the `background-image`s and Chivo web font (using system fonts now)
* switched up the colours
* made layout responsive for tablet/mobile widths
* did a little something small with the header
* tweaked the typography (for contrast and legibility)

**Comment by cvan** [comment]
live demo temporarily pushed to https://cvan.io/webvr.info/

**Comment by toji** [comment]
This is all sorts of great! Thank you! (And sorry for the slow merge. Excuse: Baby)

**Comment by cvan** [comment]
no worries at all. congratulations very, very much! 👶 🎉

**Pull request merged**
