### PR TITLE
Support videoUrl parameter in 360 video sample

### PR DESCRIPTION
**Pull request by huningxin**
This is used to change video for testing purpose.

@toji, PTAL. Thanks!

### CODE REVIEW

**Comment by huningxin** [comment]
The example usage would be like

https://huningxin.github.io/webvr.info/samples/XX-360-video.html?enablePerformanceMonitoring=true&videoUrl=https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b4/Wikimania_2016_Hackathon_360.webm/Wikimania_2016_Hackathon_360.webm.480p.webm

@toji , WDYT?

**Comment by huningxin** [comment]
@toji , any thoughts?

**Comment by huningxin** [comment]
@toji, any feedbacks? Thanks!

**Comment by toji** [comment]
Sorry, I had overlooked this because I thought it was the same as the previous 360 video pull request. LGTM.

**Comment by huningxin** [comment]
no worries. Thanks much!

**Pull request merged**
